### ISSUE TITLE
Quaternions Checklist

### ISSUE THREAD

**Issue by matthras** [9th-circle/Anathema.Vectors#1]
# Defining Object
- [ ] Define quaternion: 4-length vector, all real numbers (floats)

# Operations on Quaternions
- [ ] Adding & subtracting
- [ ] Scalar multiplication
- [ ] Hamilton product (i.e. product)
- [ ] Inverse
- [ ] Dot product
- [ ] Conjugate
- [ ] Norm

# Conversions
- [ ] Axis-angle to quaternion
- [ ] Quaternion to axis-angle
- [ ] 3x3 Rotation matrix to quaternion
- [ ] Quaternion to 3x3 rotation matrix

# Sources
* Wikipedia: https://en.wikipedia.org/wiki/Quaternion
* Rotation Quaternions: https://danceswithcode.net/engineeringnotes/quaternions/quaternions.html

Add/edit new details as required

**Comment by blame-lewis** [comment]
Looks amazing :)
Stuff to add:
- Complex types
- Double precision floating point
- Test coverage

**Comment by blame-lewis** [comment]
Also!
Are we able to slerp with those operators provided? Is it possible to create a dedicated slerp function also?
