### ISSUE TITLE
Complex Numbers Checklist

### ISSUE THREAD

**Issue by matthras** [9th-circle/Anathema.Vectors#2]
Object
- [x] 2-length vector, two real numbers

Operations on Complex Numbers
- [x] Addition & subtraction
- [x] Multiplying
- [x] Dividing
- [x] Conjugate
- [x] Norm
- [x] Argument (angle)

Conversions
- [x] Complex number to rotation matrix
- [] Rotation matrix to complex number (to go into `mat2.cs` and `dmat2.cs`)

Pull Request Checks [Added 6/11]
- [] Implementation
- [] Unit tests
- [] A section in the README that has been left for complex/quats
- [] Tick off anything in the TODO file
- [] Update the copyright to add yourself (last contributor goes to the top)

Update [14/11/23] Removed polar form conversions due to redundancy

**Comment by blame-lewis** [comment]
Complex to rotation matrix (and vice versa) might be useful in some cases. Doesn't seem like it would be absurdly hard to do?

**Comment by blame-lewis** [comment]
Pull request checklist now lives in https://github.com/9th-circle/Anathema.Vectors/blob/main/CONTRIBUTING.md
